# Codecov configuration for Polymarket MCP Server

coverage:
  precision: 2
  round: down
  range: "80...100"

  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_ci_failed: error

    patch:
      default:
        target: 80%
        threshold: 5%

  ignore:
    - "tests/"
    - "**/__pycache__/"
    - "**/venv/"
    - "**/site-packages/"

comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

flags:
  unittests:
    paths:
      - src/
    carryforward: true
